# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inteliside < Formula
  desc "CLI del Marketplace de Plugins Inteliside para Claude Code"
  homepage "https://github.com/Intelliaa/inteliside-cli"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Intelliaa/inteliside-cli/releases/download/v1.2.2/inteliside_1.2.2_darwin_amd64.tar.gz"
      sha256 "ef2993be9b0636fd4f37094b3b8c1d30c63bfe0dc301a603b4105bc4d9dc96aa"

      define_method(:install) do
        bin.install "inteliside"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Intelliaa/inteliside-cli/releases/download/v1.2.2/inteliside_1.2.2_darwin_arm64.tar.gz"
      sha256 "bca5fbb70e86abcdddabc1b2b0801b9a79caca6b21db6e5cdc7c0a82bc583754"

      define_method(:install) do
        bin.install "inteliside"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Intelliaa/inteliside-cli/releases/download/v1.2.2/inteliside_1.2.2_linux_amd64.tar.gz"
      sha256 "2d635482498cc4fda9ff0a147009104f8cde4ffb9a28c4aca76752205edad2fb"
      define_method(:install) do
        bin.install "inteliside"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Intelliaa/inteliside-cli/releases/download/v1.2.2/inteliside_1.2.2_linux_arm64.tar.gz"
      sha256 "67938f8bfe35cbc2aac3d523034828cd4e6c62a0d4bdaf44f36eb87d5191bce1"
      define_method(:install) do
        bin.install "inteliside"
      end
    end
  end

  test do
    system "#{bin}/inteliside", "version"
  end
end
